version: '3.5'
services:
  db:
    container_name: postgres
    image: postgres:9.6
    env_file: dev-env
    volumes:
      - pg-data:/var/lib/postgresql/data

  api:
    container_name: api
    build: .
    env_file: dev-env
    command: ["sh", "scripts/start.sh"]
    ports:
      - 8000:8000
    volumes:
      - .:/smi-slave
    networks:
      - smi-slave
      - default
    depends_on:
      - db

volumes:
  pg-data: {}

networks:
  smi-slave:
    name: smi-slave
